### ISSUE TITLE
Library cannot be used during build step.

### ISSUE THREAD

**Issue by simonyeldon** [platformsh/platformsh-nodejs-helper#7]
I am trying to use this library during a build step, but I get an error because the environment variables haven't been used yet.

```
    W: /app/node_modules/platformsh/lib/platformsh.min.js:1
    W: (function (exports, require, module, __filename, __dirname) { function num_of_cpus(){try{return process.env.OMP_NUM_THREADS?process.env.OMP_NUM_THREADS:Math.ceil(jsonConfig.info.limits.cpu)}catch(n){throw new Error("Could not get number of cpus")}}function read_base64_json(n){try{return JSON.parse(new Buffer(process.env[n],"base64").toString())}catch(o){throw new Error(`no ${n} environment variable`)}}function config(){if(!process.env.PLATFORM_PROJECT)throw Error("This is not running on platform.sh");return{application:read_base64_json("PLATFORM_APPLICATION"),relationships:read_base64_json("PLATFORM_RELATIONSHIPS"),variables:read_base64_json("PLATFORM_VARIABLES"),application_name:process.env.PLATFORM_APPLICATION_NAME,app_dir:process.env.PLATFORM_APP_DIR,environment:process.env.PLATFORM_ENVIRONMENT,project:process.env.PLATFORM_PROJECT,routes:read_base64_json("PLATFORM_ROUTES"),tree_id:process.env.PLATFORM_TREE_ID,project_entropy:process.env.PLATFORM_PROJEC
    W: 
    W: Error: no PLATFORM_RELATIONSHIPS environment variable
    W:     at read_base64_json (/app/node_modules/platformsh/lib/platformsh.min.js:1:363)
    W:     at Object.config (/app/node_modules/platformsh/lib/platformsh.min.js:1:581)
    W:     at Object.<anonymous> (/app/getGraphqlEndpoint.js:1:100)
    W:     at Module._compile (module.js:643:30)
    W:     at Object.Module._extensions..js (module.js:654:10)
    W:     at Module.load (module.js:556:32)
    W:     at tryModuleLoad (module.js:499:12)
    W:     at Function.Module._load (module.js:491:3)
    W:     at Function.Module.runMain (module.js:684:10)
    W:     at startup (bootstrap_node.js:187:16)
```

**Comment by Crell** [comment]
Hi @simonyeldon.  We are actually deprecating this library in favor of a new one, which should play much better with the build phase (among many other improvements): https://github.com/platformsh/config-reader-nodejs

Please use that instead.
